### ISSUE TITLE
[Remaster] Problem with weakness to holy from champion strikes

### ISSUE THREAD

**Issue by Suldrun45** [MrVauxs/PF2e-Target-Damage#68] opened 2023-11-17 13:42 UTC
It would seem that the way the (Un)holy damage is applied is different from how it usualy works. 
I have a champion with the Tenets of Good on it. This makes all his strikes "Holy", granting those strikes the Holy trait.
If I strike a creature weak to Holy (a succubus for example) with a Strike dealing Spirit damage, the weakness should trigger.

It does if I use the standard "Damage" button of the base PF2e interface, but if I use the target-specific button added by this module to apply the damage to the target, the weakness is not triggered.

![image](https://github.com/MrVauxs/PF2e-Target-Damage/assets/49712710/c9df54d3-d1ae-43fd-baa7-293d670e71cb)

**Comment by MrVauxs** [comment] 2023-11-17 13:54
Duplicate of #65

**Closed as completed by MrVauxs** 2023-11-17 13:54 UTC
